version: '3.1'

services:

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080